config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: [:index, :create] do
    resource :votes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :dislikes
  has_many :likes

  default_scope { order(created_at: :desc) }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post
end

app/models/vote/dislike.rb
class Dislike < Vote
  before_create :update_dislikes

  private

  def update_dislikes
    post.update(dislikes_count: post.dislikes_count + 1)
  end
end

app/models/vote/like.rb
class Like < Vote
  before_create :update_likes

  private

  def update_likes
    post.update(likes_count: post.likes_count + 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    if @post = Post.create(post_params)
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post)
          .permit(:description, :title)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create

    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.dislikes.create

    respond_to do |format|
      format.js {}
      format.html {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voteape</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="app-header">
        <h2 class="brand-name">Voteape</h2>
      </div>

      <div class="app-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, rows: 5, placeholder: 'Description', class: 'form-control' %>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-2">
        <%= f.submit 'Save', class: 'btn btn-success btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card m-b">
  <div class="card-block">
    <p>
      <strong><%= post.title %></strong>
    </p>
    <%= post.description %>
  </div>

  <div class="card-block">
    <div class="vote">
      <div class="counter likes" id="post-<%= post.id %>">
        <%= post.likes_count %>
      </div>
      <div class="link">
        <%= link_to post_votes_path(post), method: :post, remote: true, class: 'text-success' do %>
          <i class="fa fa-thumbs-up"></i>
          Good
        <% end %>
      </div>
    </div>

    <div class="vote">
      <div class="counter dislikes" id="post-<%= post.id %>">
        <%= post.dislikes_count %>
      </div>
      <div class="link">
        <%= link_to post_votes_path(post), method: :delete, remote: true, class: 'text-danger' do %>
          <i class="fa fa-thumbs-down"></i>
          Bad
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h4 class="m-b">
  Posts
  <small class="text-muted"> <%= @posts.count %></small>
</h4>
<hr>

<%= render 'form' %>

<%- if @posts.empty? %>
  <div class="text-muted">
    <p>No posts yet</p>
  </div>
<% else %>
  <%= render @posts %>
<% end %>

app/views/votes/create.js.erb
$("#post-<%= @post.id %>.counter.likes").text("<%= @post.reload.likes_count %>")

app/views/votes/destroy.js.erb
$("#post-<%= @post.id %>.counter.dislikes").text("<%= @post.reload.dislikes_count %>")